export const names = [
  'Recare Aguila',
  'Lagade Alejandro',
  'Sogoni Ambas',
  'Reyta Andal',
  'Lubay Aquino',
  'Austria Arriola',
  'Cequeña Avellar',
  'Gal Bagasbas',
  'Apsay Beconia',
  'Landicho Bondoc',
  'Bautista Bron',
  'Ferrer Carrio',
  'Duenas Catipon',
  'Baylon Compa',
  'Buenaventura Cuerdo',
  'Villanueva De Guzman',
  'Carlos Vasquez',
  'Ricohermozo Villanueva',
  'Millar Villaraza',
  'Bonifacio Ambrosio',
  'Ubina Ansay',
  'Entico Aquino',
  'Apsay Balbon',
  'Tipace Baluyot',
  'Mirabona Cabojoc',
  'Aparece Cepedoza',
  'Goma Guevarra',
  'Dacles Orit',
  'Billuga Rabusa',
  'Fajardo Ricarte',
  'Taperla Romero',
  'Abayon Tilad Jr',
];
